<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  
  <title>Revit API 斜楼板 | 秋味笔记</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <meta name="description" content="写点干货，其实也不是很干，不过在TheBuildingCoder，Forum还有叶老师的博客里边都找不到对应的资料。问题其实很简单，如何用Revit API创建斜楼板。
Revit API中的NewFloor()一般用来创建楼板，不过方法中只接受平面的轮廓线，若轮廓线不在平面上则报错，提示轮廓线无效。叶老师的博客中介绍斜楼板无法使用NewFloor()，需要使用NewSlab()方法。TheBui">
<meta property="og:type" content="article">
<meta property="og:title" content="Revit API 斜楼板">
<meta property="og:url" content="http://http://autumnflavor.com/2016/11/13/Revit-API-斜楼板/index.html">
<meta property="og:site_name" content="秋味笔记">
<meta property="og:description" content="写点干货，其实也不是很干，不过在TheBuildingCoder，Forum还有叶老师的博客里边都找不到对应的资料。问题其实很简单，如何用Revit API创建斜楼板。
Revit API中的NewFloor()一般用来创建楼板，不过方法中只接受平面的轮廓线，若轮廓线不在平面上则报错，提示轮廓线无效。叶老师的博客中介绍斜楼板无法使用NewFloor()，需要使用NewSlab()方法。TheBui">
<meta property="og:updated_time" content="2016-11-13T07:18:52.377Z">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Revit API 斜楼板">
<meta name="twitter:description" content="写点干货，其实也不是很干，不过在TheBuildingCoder，Forum还有叶老师的博客里边都找不到对应的资料。问题其实很简单，如何用Revit API创建斜楼板。
Revit API中的NewFloor()一般用来创建楼板，不过方法中只接受平面的轮廓线，若轮廓线不在平面上则报错，提示轮廓线无效。叶老师的博客中介绍斜楼板无法使用NewFloor()，需要使用NewSlab()方法。TheBui">
  
    <link rel="alternative" href="/atom.xml" title="秋味笔记" type="application/atom+xml">
  
  
    <link rel="icon" href="/img/615.png">
  
  <link rel="stylesheet" href="/css/style.css" type="text/css">
  <link rel="stylesheet" href="/font-awesome/css/font-awesome.min.css">
  <link rel="apple-touch-icon" href="/apple-touch-icon.png">
  
</head>
<body>
  <div id="container">
    <div class="left-col">
    <div class="overlay"></div>
<div class="intrude-less">
    <header id="header" class="inner">
        <a href="/" class="profilepic">
            
            <img lazy-src="/img/avatar.png" class="js-avatar">
            
        </a>

        <hgroup>
          <h1 class="header-author"><a href="/">秋味</a></h1>
        </hgroup>

        
        <p class="header-subtitle">前沿BIM、参数化与建筑可视化研究，致力于推进下一代计算机辅助设计。</p>
        
                


        
            <div id="switch-btn" class="switch-btn">
                <div class="icon">
                    <div class="icon-ctn">
                        <div class="icon-wrap icon-house" data-idx="0">
                            <div class="birdhouse"></div>
                            <div class="birdhouse_holes"></div>
                        </div>
                        <div class="icon-wrap icon-ribbon hide" data-idx="1">
                            <div class="ribbon"></div>
                        </div>
                        
                        <div class="icon-wrap icon-link hide" data-idx="2">
                            <div class="loopback_l"></div>
                            <div class="loopback_r"></div>
                        </div>
                        
                        
                        <div class="icon-wrap icon-me hide" data-idx="3">
                            <div class="user"></div>
                            <div class="shoulder"></div>
                        </div>
                        
                    </div>
                    
                </div>
                <div class="tips-box hide">
                    <div class="tips-arrow"></div>
                    <ul class="tips-inner">
                        <li>菜单</li>
                        <li>标签</li>
                        
                        <li>友情链接</li>
                        
                        
                        <li>关于我</li>
                        
                    </ul>
                </div>
            </div>
        

        <div id="switch-area" class="switch-area">
            <div class="switch-wrap">
                <section class="switch-part switch-part1">
                    <nav class="header-menu">
                        <ul>
                        
                            <li><a href="/">主页</a></li>
                        
                            <li><a href="/archives/">所有文章</a></li>
                        
                            <li><a href="/tags/">标签云</a></li>
                        
                            <li><a href="/about/">关于我</a></li>
                        
                        </ul>
                    </nav>
                    <nav class="header-nav">
                        <ul class="social">
                            
                                <li id="新浪微博"><a class="新浪微博" target="_blank" href="http://weibo.com/frobo" title="新浪微博"></a></li>
                            
                                <li id="GitHub"><a class="GitHub" target="_blank" href="https://github.com/LiuBoChangSha/LiuBoChangSha.github.io" title="GitHub"></a></li>
                            
                                <li id="RSS"><a class="RSS" target="_blank" href="/atom.xml" title="RSS"></a></li>
                            
                                <li id="微信"><a class="微信" target="_blank" href="http://7xpt80.com1.z0.glb.clouddn.com/AutumnFlavorWx.png" title="微信"></a></li>
                            
                        </ul>
                    </nav>
                </section>
                
                
                <section class="switch-part switch-part2">
                    <div class="widget tagcloud" id="js-tagcloud">
                        <li><a href="/tags/64位/" style="font-size: 10px;">64位</a></li> <li><a href="/tags/AVF/" style="font-size: 10px;">AVF</a></li> <li><a href="/tags/Access/" style="font-size: 10px;">Access</a></li> <li><a href="/tags/ExporterIFCUtils/" style="font-size: 10px;">ExporterIFCUtils</a></li> <li><a href="/tags/FilteredElementCollector/" style="font-size: 10px;">FilteredElementCollector</a></li> <li><a href="/tags/Modelo/" style="font-size: 10px;">Modelo</a></li> <li><a href="/tags/NewFloor/" style="font-size: 10px;">NewFloor</a></li> <li><a href="/tags/Revit/" style="font-size: 20px;">Revit</a></li> <li><a href="/tags/Revit-API-2014/" style="font-size: 10px;">Revit API 2014</a></li> <li><a href="/tags/VR/" style="font-size: 10px;">VR</a></li> <li><a href="/tags/WebGL/" style="font-size: 10px;">WebGL</a></li> <li><a href="/tags/mdb/" style="font-size: 10px;">mdb</a></li> <li><a href="/tags/oppening/" style="font-size: 10px;">oppening</a></li> <li><a href="/tags/profile/" style="font-size: 10px;">profile</a></li> <li><a href="/tags/shader/" style="font-size: 10px;">shader</a></li> <li><a href="/tags/wall/" style="font-size: 10px;">wall</a></li> <li><a href="/tags/凯威特/" style="font-size: 20px;">凯威特</a></li> <li><a href="/tags/地形/" style="font-size: 10px;">地形</a></li> <li><a href="/tags/地理空间数据云/" style="font-size: 10px;">地理空间数据云</a></li> <li><a href="/tags/斜楼板/" style="font-size: 10px;">斜楼板</a></li> <li><a href="/tags/族名称/" style="font-size: 10px;">族名称</a></li> <li><a href="/tags/网架，参数化/" style="font-size: 20px;">网架，参数化</a></li>
                    </div>
                </section>
                
                
                
                <section class="switch-part switch-part3">
                    <div id="js-friends">
                    
                      <a target="_blank" class="main-nav-link switch-friends-link" href="https://hexo.io">Hexo</a>
                    
                      <a target="_blank" class="main-nav-link switch-friends-link" href="https://pages.github.com/">GitHub</a>
                    
                    </div>
                </section>
                

                
                
                <section class="switch-part switch-part4">
                
                    <div id="js-aboutme">优秀很容易，卓越很难。</div>
                </section>
                
            </div>
        </div>
    </header>                
</div>
    </div>
    <div class="mid-col">
      <nav id="mobile-nav">
      <div class="overlay">
          <div class="slider-trigger"></div>
          <h1 class="header-author js-mobile-header hide"><a href="/" title="回到主页">秋味</a></h1>
      </div>
    <div class="intrude-less">
        <header id="header" class="inner">
            <a href="/" class="profilepic">
                <img lazy-src="/img/avatar.png" class="js-avatar">
            </a>
            <hgroup>
              <h1 class="header-author"><a href="/" title="回到主页">秋味</a></h1>
            </hgroup>
            
            <p class="header-subtitle">前沿BIM、参数化与建筑可视化研究，致力于推进下一代计算机辅助设计。</p>
            
            <nav class="header-menu">
                <ul>
                
                    <li><a href="/">主页</a></li>
                
                    <li><a href="/archives/">所有文章</a></li>
                
                    <li><a href="/tags/">标签云</a></li>
                
                    <li><a href="/about/">关于我</a></li>
                
                <div class="clearfix"></div>
                </ul>
            </nav>
            <nav class="header-nav">
                        <ul class="social">
                            
                                <li id="新浪微博"><a class="新浪微博" target="_blank" href="http://weibo.com/frobo" title="新浪微博"></a></li>
                            
                                <li id="GitHub"><a class="GitHub" target="_blank" href="https://github.com/LiuBoChangSha/LiuBoChangSha.github.io" title="GitHub"></a></li>
                            
                                <li id="RSS"><a class="RSS" target="_blank" href="/atom.xml" title="RSS"></a></li>
                            
                                <li id="微信"><a class="微信" target="_blank" href="http://7xpt80.com1.z0.glb.clouddn.com/AutumnFlavorWx.png" title="微信"></a></li>
                            
                        </ul>
            </nav>
        </header>                
    </div>
</nav>
      <div class="body-wrap"><article id="post-Revit-API-斜楼板" class="article article-type-post" itemscope itemprop="blogPost">
  
    <div class="article-meta">
      <a href="/2016/11/13/Revit-API-斜楼板/" class="article-date">
      <time datetime="2016-11-13T06:10:22.000Z" itemprop="datePublished">2016-11-13</time>
</a>
    </div>
  
  <div class="article-inner">
    
      <input type="hidden" class="isFancy" />
    
    
      <header class="article-header">
        
  
    <h1 class="article-title" itemprop="name">
      Revit API 斜楼板
    </h1>
  

      </header>
      
      <div class="article-info article-info-post">
        
    <div class="article-category tagcloud">
    <a class="article-category-link" href="/categories/Revit-API/">Revit API</a>
    </div>


        
    <div class="article-tag tagcloud">
        <ul class="article-tag-list"><li class="article-tag-list-item"><a class="article-tag-list-link" href="/tags/NewFloor/">NewFloor</a></li><li class="article-tag-list-item"><a class="article-tag-list-link" href="/tags/Revit-API-2014/">Revit API 2014</a></li><li class="article-tag-list-item"><a class="article-tag-list-link" href="/tags/斜楼板/">斜楼板</a></li></ul>
    </div>

        <div class="clearfix"></div>
      </div>
      
    
    <div class="article-entry" itemprop="articleBody">
      
          
        <p>写点干货，其实也不是很干，不过在TheBuildingCoder，Forum还有叶老师的博客里边都找不到对应的资料。问题其实很简单，如何用Revit API创建斜楼板。</p>
<p>Revit API中的NewFloor()一般用来创建楼板，不过方法中只接受平面的轮廓线，若轮廓线不在平面上则报错，提示轮廓线无效。叶老师的博客中介绍斜楼板无法使用NewFloor()，需要使用NewSlab()方法。TheBuildingCoder中的介绍也类似，不过为使得模型前后更一致切符合用户习惯，本文记录了我在Revit中使用NewFloor() API来成功创建斜楼板的过程。</p>
<h3 id="u73B0_u6709_u8D44_u6599"><a href="#u73B0_u6709_u8D44_u6599" class="headerlink" title="现有资料"></a>现有资料</h3><p>叶老师的博客：<a href="http://blog.csdn.net/joexiongjin/article/details/20150887" target="_blank" rel="external">如何用API来创建斜板 </a></p>
<p>TheBuildingCoder：<a href="/"></a>（爬墙失败，链接后面再补）<br><a id="more"></a></p>
<h3 id="UI_u4E0A_u7684_u64CD_u4F5C"><a href="#UI_u4E0A_u7684_u64CD_u4F5C" class="headerlink" title="UI上的操作"></a>UI上的操作</h3><p>UI上也是无法直接创建斜楼板的，需要先创建一块平楼板，然后在修改菜单中的形状编辑栏使用修改子图元工具来编辑楼板上的点，通过设置每个点的偏移来创建斜楼板。</p>
<h3 id="API_u64CD_u4F5C"><a href="#API_u64CD_u4F5C" class="headerlink" title="API操作"></a>API操作</h3><p>在API Document中搜索，可以发现Floor类中有一个和UI上形状编辑对应的属性，类型为SlabShapeEditor。这个类恰好也有一个方法对应UI的修改子图元功能：ModifySubElement(SlabShapeVertex, Double)。于是我使用了下面的代码来创建一块斜楼板：<br><figure class="highlight cpp"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">void</span> <span class="title">CreateSlopedFloor</span><span class="params">(FloorType ft, Level level)</span></span><br><span class="line">        </span>&#123;</span><br><span class="line">            Document doc = ft.Document;</span><br><span class="line">            XYZ pt1 = <span class="keyword">new</span> XYZ(<span class="number">0</span>, <span class="number">0</span>, <span class="number">0</span>);</span><br><span class="line">            XYZ pt2 = <span class="keyword">new</span> XYZ(<span class="number">100</span>, <span class="number">0</span>, <span class="number">0</span>);</span><br><span class="line">            XYZ pt3 = <span class="keyword">new</span> XYZ(<span class="number">100</span>, <span class="number">100</span>, <span class="number">0</span>);</span><br><span class="line">            XYZ pt4 = <span class="keyword">new</span> XYZ(<span class="number">0</span>, <span class="number">100</span>, <span class="number">0</span>);</span><br><span class="line">            CurveArray profile = <span class="keyword">new</span> CurveArray();</span><br><span class="line">            profile.Append(Line.CreateBound(pt1, pt2));</span><br><span class="line">            profile.Append(Line.CreateBound(pt2, pt3));</span><br><span class="line">            profile.Append(Line.CreateBound(pt3, pt4));</span><br><span class="line">            profile.Append(Line.CreateBound(pt4, pt1));</span><br><span class="line"></span><br><span class="line">            Floor <span class="built_in">floor</span> = doc.Create.NewFloor(profile, ft, level, <span class="literal">true</span>);</span><br><span class="line">            <span class="built_in">floor</span>.Document.Regenerate();</span><br><span class="line">            <span class="keyword">double</span> offset = <span class="number">30</span>;</span><br><span class="line">            <span class="comment">// 获取SlabShapeEditor</span></span><br><span class="line">            SlabShapeEditor slabEditor = <span class="built_in">floor</span>.SlabShapeEditor;</span><br><span class="line">            slabEditor.DrawPoint(pt1);</span><br><span class="line">            slabEditor.DrawPoint(pt2);</span><br><span class="line">            slabEditor.DrawPoint(pt3);</span><br><span class="line">            slabEditor.DrawPoint(pt4);</span><br><span class="line">            var vertices = slabEditor.SlabShapeVertices;</span><br><span class="line">            <span class="comment">// 修改第三点和第四点的偏移值</span></span><br><span class="line">            foreach (SlabShapeVertex vertex in vertices)</span><br><span class="line">            &#123;</span><br><span class="line">                <span class="keyword">if</span> (vertex.Position.IsAlmostEqualTo(pt3))</span><br><span class="line">                &#123;</span><br><span class="line">                    slabEditor.ModifySubElement(vertex, offset);</span><br><span class="line">                &#125;</span><br><span class="line">                <span class="keyword">else</span> <span class="keyword">if</span> (vertex.Position.IsAlmostEqualTo(pt4))</span><br><span class="line">                &#123;</span><br><span class="line">                    slabEditor.ModifySubElement(vertex, offset);</span><br><span class="line">                &#125;</span><br><span class="line">            &#125;</span><br><span class="line">        &#125;</span><br></pre></td></tr></table></figure></p>
<p>似乎并没有错误，编译和执行也都没有问题，但是创建出来的结果却出乎意料，楼板还是平的。。。此时只能够Debug走一遍代码，经过一番搜寻发现了问题所在：slabEditor.SlabShapeVertices数量为零。此时对第三点和第四点的遍历修改操作不会被执行，因此偏移值没有成功设定。<br>回过头再仔细看UI操作，又有了新的发现：正常的楼板和斜楼板被选中后是不同的状态，斜楼板被选中后，四周会有角点和折线（分别对应SlabShapeVertices和SlabShapeCrease），而平楼板则什么都没有，因此角点和折线显然不是一开始就存在于SlabShapEditor中的，而是后来添加上的。而使用SlabShapeEditor.DrawPoint()方法则可添加角点。<br>我把代码修改为以下代码后，此时成功的创建了一块斜楼板：<br><figure class="highlight cpp"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">void</span> <span class="title">CreateSlopedFloor</span><span class="params">(FloorType ft, Level level)</span></span><br><span class="line">        </span>&#123;</span><br><span class="line">            Document doc = ft.Document;</span><br><span class="line">            XYZ pt1 = <span class="keyword">new</span> XYZ(<span class="number">0</span>, <span class="number">0</span>, <span class="number">0</span>);</span><br><span class="line">            XYZ pt2 = <span class="keyword">new</span> XYZ(<span class="number">100</span>, <span class="number">0</span>, <span class="number">0</span>);</span><br><span class="line">            XYZ pt3 = <span class="keyword">new</span> XYZ(<span class="number">100</span>, <span class="number">100</span>, <span class="number">0</span>);</span><br><span class="line">            XYZ pt4 = <span class="keyword">new</span> XYZ(<span class="number">0</span>, <span class="number">100</span>, <span class="number">0</span>);</span><br><span class="line">            CurveArray profile = <span class="keyword">new</span> CurveArray();</span><br><span class="line">            profile.Append(Line.CreateBound(pt1, pt2));</span><br><span class="line">            profile.Append(Line.CreateBound(pt2, pt3));</span><br><span class="line">            profile.Append(Line.CreateBound(pt3, pt4));</span><br><span class="line">            profile.Append(Line.CreateBound(pt4, pt1));</span><br><span class="line"></span><br><span class="line">            Floor <span class="built_in">floor</span> = doc.Create.NewFloor(profile, ft, level, <span class="literal">true</span>);</span><br><span class="line">            <span class="built_in">floor</span>.Document.Regenerate();</span><br><span class="line">            <span class="keyword">double</span> offset = <span class="number">30</span>;</span><br><span class="line">            <span class="comment">// 获取SlabShapeEditor</span></span><br><span class="line">            SlabShapeEditor slabEditor = <span class="built_in">floor</span>.SlabShapeEditor;</span><br><span class="line">            <span class="comment">// 绘制角点，这里只需要修改角点偏移，因此不需要添加折痕线</span></span><br><span class="line">            slabEditor.DrawPoint(pt1);</span><br><span class="line">            slabEditor.DrawPoint(pt2);</span><br><span class="line">            slabEditor.DrawPoint(pt3);</span><br><span class="line">            slabEditor.DrawPoint(pt4);</span><br><span class="line">            var vertices = slabEditor.SlabShapeVertices;</span><br><span class="line">            <span class="comment">// 修改第三点和第四点的偏移值</span></span><br><span class="line">            foreach (SlabShapeVertex vertex in vertices)</span><br><span class="line">            &#123;</span><br><span class="line">                <span class="keyword">if</span> (vertex.Position.IsAlmostEqualTo(pt3))</span><br><span class="line">                &#123;</span><br><span class="line">                    slabEditor.ModifySubElement(vertex, offset);</span><br><span class="line">                &#125;</span><br><span class="line">                <span class="keyword">else</span> <span class="keyword">if</span> (vertex.Position.IsAlmostEqualTo(pt4))</span><br><span class="line">                &#123;</span><br><span class="line">                    slabEditor.ModifySubElement(vertex, offset);</span><br><span class="line">                &#125;</span><br><span class="line">            &#125;</span><br><span class="line">        &#125;</span><br></pre></td></tr></table></figure></p>

           
    </div>
    
  </div>
  
    
    <div class="copyright">
        <p><span>本文标题:</span><a href="/2016/11/13/Revit-API-斜楼板/">Revit API 斜楼板</a></p>
        <p><span>文章作者:</span><a href="/" title="访问 秋味 的个人博客">秋味</a></p>
        <p><span>发布时间:</span>2016年11月13日 - 14时10分</p>
        <p><span>最后更新:</span>2016年11月13日 - 15时18分</p>
        <p>
            <span>原始链接:</span><a class="post-url" href="/2016/11/13/Revit-API-斜楼板/" title="Revit API 斜楼板">http://http://autumnflavor.com/2016/11/13/Revit-API-斜楼板/</a>
            <span class="copy-path" data-clipboard-text="原文: http://http://autumnflavor.com/2016/11/13/Revit-API-斜楼板/　　作者: 秋味" title="点击复制文章链接"><i class="fa fa-clipboard"></i></span>
            <script src="/js/clipboard.min.js"></script>
            <script> var clipboard = new Clipboard('.copy-path'); </script>
        </p>
        <p>
            <span>许可协议:</span><i class="fa fa-creative-commons"></i> <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/cn/" title="中国大陆 (CC BY-NC-SA 3.0 CN)">"署名-非商用-相同方式共享 3.0"</a> 转载请保留原文链接及作者。
        </p>
    </div>



    <nav id="article-nav">
        
            <div id="article-nav-newer" class="article-nav-title">
                <a href="/2016/11/21/GH-单层凯威特网架/">
                    GH | 凯威特单层网壳
                </a>
            </div>
        
        
            <div id="article-nav-older" class="article-nav-title">
                <a href="/2016/07/16/没有地形文件的情况下建立项目地形/">
                    没有地形文件的情况下建立项目地形
                </a>
            </div>
        
    </nav>

  
</article>

    <div id="toc" class="toc-article">
    <strong class="toc-title">文章目录</strong>
    <ol class="toc"><li class="toc-item toc-level-3"><a class="toc-link" href="#u73B0_u6709_u8D44_u6599"><span class="toc-number">1.</span> <span class="toc-text">现有资料</span></a></li><li class="toc-item toc-level-3"><a class="toc-link" href="#UI_u4E0A_u7684_u64CD_u4F5C"><span class="toc-number">2.</span> <span class="toc-text">UI上的操作</span></a></li><li class="toc-item toc-level-3"><a class="toc-link" href="#API_u64CD_u4F5C"><span class="toc-number">3.</span> <span class="toc-text">API操作</span></a></li></ol>
</div>
<style>
    .left-col .switch-btn {
        display: none;
    }
    .left-col .switch-area {
        display: none;
    }
</style>

<input type="button" id="tocButton" value="隐藏目录"  title="点击按钮隐藏或者显示文章目录">

<script src="http://7.url.cn/edu/jslib/comb/require-2.1.6,jquery-1.9.1.min.js" type="text/javascript"></script>
<script>
    var toc_button = document.getElementById("tocButton");
    var toc_div = document.getElementById("toc");
    toc_button.onclick=function() {
        if (toc_div.style.display == "none") {
            toc_div.style.display = "block";
            toc_button.value = "隐藏目录";
            document.getElementById("switch-btn").style.display = "none";
            document.getElementById("switch-area").style.display = "none";
        }
        else {
            toc_div.style.display = "none";
            toc_button.value = "显示目录";
            document.getElementById("switch-btn").style.display = "block";
            document.getElementById("switch-area").style.display = "block";
        }
    }

    if ($(".toc").length < 1) {
        $("#toc").css("display","none");
        $("#tocButton").css("display","none");
        $(".switch-btn").css("display","block");
        $(".switch-area").css("display","block");
    }
</script>




<div class="share">
    <div class="bdsharebuttonbox">
    <a href="#" class="bds_more" data-cmd="more"></a>
    <a href="#" class="bds_tsina" data-cmd="tsina" title="分享到新浪微博"></a>
    <a href="#" class="bds_sqq" data-cmd="sqq" title="分享给 QQ 好友"></a>
    <a href="#" class="bds_copy" data-cmd="copy" title="复制网址"></a>
    <a href="#" class="bds_mail" data-cmd="mail" title="通过邮件分享"></a>
    <a href="#" class="bds_weixin" data-cmd="weixin" title="生成文章二维码"></a>
    </div>
    <script>
        window._bd_share_config={
            "common":{"bdSnsKey":{},"bdText":"","bdMini":"2","bdMiniList":false,"bdPic":"","bdStyle":"0","bdSize":"24"},"share":{}};with(document)0[(getElementsByTagName('head')[0]||body).appendChild(createElement('script')).src='http://bdimg.share.baidu.com/static/api/js/share.js?v=89860593.js?cdnversion='+~(-new Date()/36e5)];
    </script>
</div>



    
      <div class="duoshuo" id="comments">
    <!-- 多说评论框 start -->
    <div class="ds-thread" data-thread-key="2016/11/13/Revit-API-斜楼板/" data-title="Revit API 斜楼板" data-url="http://http://autumnflavor.com/2016/11/13/Revit-API-斜楼板/"></div>
    <!-- 多说评论框 end -->
    <!-- 多说公共JS代码 start (一个网页只需插入一次) -->
    <script type="text/javascript">
    /*var duoshuoQuery = {short_name:"null"};*/
    var duoshuoQuery = {short_name:"autumnflavor"};
    (function() {
        var ds = document.createElement('script');
        ds.type = 'text/javascript';ds.async = true;
        ds.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') + '//static.duoshuo.com/embed.js';
        ds.charset = 'UTF-8';
        (document.getElementsByTagName('head')[0] 
         || document.getElementsByTagName('body')[0]).appendChild(ds);
    })();
    </script>
    <!-- 多说公共JS代码 end -->
</div>

    




    <div class="scroll" id="post-nav-button">
        
            <a href="/2016/11/21/GH-单层凯威特网架/" title="上一篇: GH | 凯威特单层网壳">
                <i class="fa fa-angle-left"></i>
            </a>
        

        <a title="文章列表"><i class="fa fa-bars"></i><i class="fa fa-times"></i></a>

        
            <a href="/2016/07/16/没有地形文件的情况下建立项目地形/" title="下一篇: 没有地形文件的情况下建立项目地形">
                <i class="fa fa-angle-right"></i>
            </a>
        
    </div>

    <ul class="post-list"><li class="post-list-item"><a class="post-list-link" href="/2017/02/18/Dynamo-单层凯威特空间网架/">Dynamo|单层凯威特空间网壳</a></li><li class="post-list-item"><a class="post-list-link" href="/2016/11/21/GH-单层凯威特网架/">GH | 凯威特单层网壳</a></li><li class="post-list-item"><a class="post-list-link" href="/2016/11/13/Revit-API-斜楼板/">Revit API 斜楼板</a></li><li class="post-list-item"><a class="post-list-link" href="/2016/07/16/没有地形文件的情况下建立项目地形/">没有地形文件的情况下建立项目地形</a></li><li class="post-list-item"><a class="post-list-link" href="/2016/07/04/Revit-API-Analysis-Visualisation-Framework/">Revit API - Analysis Visualisation Framework</a></li><li class="post-list-item"><a class="post-list-link" href="/2016/06/13/Revit-API-ExporterIFCUtils获取墙洞口及轮廓线/">Revit API - ExporterIFCUtils获取墙洞口及轮廓线</a></li><li class="post-list-item"><a class="post-list-link" href="/2016/02/15/Modelo-基于WebGL的可视化解决方案/">Modelo | 基于WebGL的可视化解决方案</a></li><li class="post-list-item"><a class="post-list-link" href="/2016/01/27/Unity3D之Standard-Shader初探/">Unity3D之Standard Shader初探</a></li><li class="post-list-item"><a class="post-list-link" href="/2016/01/14/Revit中获取族名称通用代码/">Revit中获取族名称通用代码</a></li><li class="post-list-item"><a class="post-list-link" href="/2016/01/06/Revit中调用Access数据库/">Revit中调用Access数据库</a></li><li class="post-list-item"><a class="post-list-link" href="/2016/01/05/Revit-API之元素检索优化/">Revit API之元素检索优化</a></li></ul>
    <script src="http://7.url.cn/edu/jslib/comb/require-2.1.6,jquery-1.9.1.min.js"></script>
    <script>
        $(".post-list").addClass("toc-article");
        $(".post-list-item a").attr("target","_blank");
        $("#post-nav-button > a:nth-child(2)").click(function() {
            $(".fa-bars, .fa-times").toggle();
            $(".post-list").toggle(300);
            if ($(".toc").length > 0) {
                $("#toc, #tocButton").toggle(200);
            }
            else {
                $(".switch-btn, .switch-area").toggle(200);
            }
        })
    </script>




    
        <link rel="stylesheet" href="/fancybox/jquery.fancybox.css" type="text/css">
        <script>
            var yiliaConfig = {
            fancybox: true,
            mathjax: true,
            animate: true,
            isHome: false,
            isPost: true,
            isArchive: false,
            isTag: false,
            isCategory: false,
            open_in_new: false
            }
        </script>
        


</div>
      <footer id="footer">
    <div class="outer">
        <div id="footer-info">
            <div class="footer-left">
                &copy; 2017 秋味
            </div>
            <div class="footer-right">
                Powered by <a href="http://hexo.io/" target="_blank" title="快速、简洁且高效的静态博客框架">Hexo</a>, Theme <a href="https://github.com/MOxFIVE/hexo-theme-yelee">YeLee</a>
            </div>
        </div>
        <div class="visit">
            <span id="busuanzi_container_site_pv" style='display:none'>
                <span id="site-visit" >本站到访数:
                    <span id="busuanzi_value_site_uv"></span>
                </span>
            </span>
            <span id="busuanzi_container_page_pv" style='display:none'>
                <span id="page-visit">, 本页阅读量:
                    <span id="busuanzi_value_page_pv"></span>
                </span>
            </span>
        </div>
    </div>
</footer>

    </div>
    

<script src="http://7.url.cn/edu/jslib/comb/require-2.1.6,jquery-1.9.1.min.js" type="text/javascript"></script>
<script src="/js/main.js" type="text/javascript"></script>

    <script>
        $(document).ready(function() {
            var iPad = window.navigator.userAgent.indexOf('iPad');
            if (iPad > -1 || $(".left-col").css("display") === "none") {
                var bgColorList = ["#9db3f4", "#414141", "#e5a859", "#f5dfc6", "#c084a0", "#847e72", "#cd8390", "#996731"];
                var bgColor = Math.ceil(Math.random() * (bgColorList.length - 1));
                $("body").css({"background-color": bgColorList[bgColor], "background-size": "cover"});
            }
            else {
                var backgroundnum = 5;
                var backgroundimg = "url(/background/bg-x.jpg)".replace(/x/gi, Math.ceil(Math.random() * backgroundnum));
                $("body").css({"background": backgroundimg, "background-attachment": "fixed", "background-size": "cover"});
            }
        })
    </script>




<script type="text/x-mathjax-config">
MathJax.Hub.Config({
    tex2jax: {
        inlineMath: [ ['$','$'], ["\\(","\\)"]  ],
        processEscapes: true,
        skipTags: ['script', 'noscript', 'style', 'textarea', 'pre', 'code']
    }
});

MathJax.Hub.Queue(function() {
    var all = MathJax.Hub.getAllJax(), i;
    for(i=0; i < all.length; i += 1) {
        all[i].SourceElement().parentNode.className += ' has-jax';                 
    }       
});
</script>

<script type="text/javascript" src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
</script>


<div class="scroll" id="scroll">
    <a href="#" title="返回顶部"><i class="fa fa-arrow-up"></i></a>
    <a href="#comments" title="查看评论"><i class="fa fa-comments-o"></i></a>
    <a href="#footer" title="转到底部"><i class="fa fa-arrow-down"></i></a>
</div>

<script>
    $(document).ready(function() {
        if ($("#comments").length < 1) {
            $("#scroll > a:nth-child(2)").hide();
        };
    })
</script>

<script async src="https://dn-lbstatics.qbox.me/busuanzi/2.3/busuanzi.pure.mini.js">
</script>
  </div>
</body>
</html>